### ISSUE TITLE
Apply For ability

### ISSUE THREAD

**Issue by EsterniTY** [juangranados/check_win_perfmon#1]
Hey! Nice plugin!

How about to add ability to pass some kind of variables to XML files via command line arguments?

For example:
I have five network interfaces on my server and I want to monitor a bunch of parameters on each of them. It would be easier to create Apply For rule in icinga/nagios for a list of interfaces and use single XML file instead of creating separate XML files (event using 'apply for', as I do it now). Same thought about monitoring of a list of Physical Drives...

**Comment by juangranados** [comment]
Thanks for your suggestion! I will think about it!

**Comment by juangranados** [comment]
Hey @EsterniTY! I made the enhancement that you suggested. Better late than never!
