### ISSUE TITLE
Monitoring RDMA Activity

### ISSUE THREAD

**Issue by Constey** [juangranados/check_win_perfmon#2]
Hi there,

i'm trying to monitor the rdma activity of some of our network adapters.
But I dont get it to work. I alway get the error:
`Unknown: Error creating performance counter \RDMA-Aktivität\RDMA - ausgehende Bytes/s: Die Kategorie ist nicht vorhanden.`

The Performance Counter are available like:
`Get-Counter -ListSet "RDMA-Aktivität*" | Select-Object -ExpandProperty Counter
\RDMA-Aktivität(*)\RDMA - ausgehende Frames/s
\RDMA-Aktivität(*)\RDMA - eingehende Frames/s
\RDMA-Aktivität(*)\RDMA - ausgehende Bytes/s
\RDMA-Aktivität(*)\RDMA - eingehende Bytes/s
\RDMA-Aktivität(*)\RDMA - CQ-Fehler
\RDMA-Aktivität(*)\RDMA - aktive Verbindungen
\RDMA-Aktivität(*)\RDMA - Verbindungsfehler
\RDMA-Aktivität(*)\RDMA - nicht erfolgreiche Verbindungsversuche
\RDMA-Aktivität(*)\RDMA - akzeptierte Verbindungen
\RDMA-Aktivität(*)\RDMA - initiierte Verbindungen`

Get-Counter -Counter "\RDMA-Aktivität(*)\RDMA - ausgehende Bytes/s" -SampleInterval 2 -MaxSamples 3

Timestamp                 CounterSamples
---------                 --------------
04.09.2018 16:45:23       \\SERVER-01\rdma-aktivität(hp infiniband fdr-ethernet 10gb-40gb 2-port 544+qsfp ethernet adapter
                          #2)\rdma - ausgehende bytes/s :
                          7487,17451911425

                          \\SERVER-01\rdma-aktivität(hp infiniband fdr-ethernet 10gb-40gb 2-port 544+qsfp ethernet
                          adapter)\rdma - ausgehende bytes/s :
                          1072977,99572484

                          \\SERVER-01\rdma-aktivität(hp infiniband fdr-ethernet 10gb-40gb 2-port 544+qsfp ethernet adapter
                          #4)\rdma - ausgehende bytes/s :
                          956572,397751331

                          \\SERVER-01\rdma-aktivität(hp infiniband fdr-ethernet 10gb-40gb 2-port 544+flr-qsfp ethernet adapter
                          #2)\rdma - ausgehende bytes/s :
                          776592,701791055

                          \\SERVER-01\rdma-aktivität(hp infiniband fdr-ethernet 10gb-40gb 2-port 544+flr-qsfp ethernet
                          adapter)\rdma - ausgehende bytes/s :
                          1013699,53933217

                          \\SERVER-01\rdma-aktivität(hp infiniband fdr-ethernet 10gb-40gb 2-port 544+qsfp ethernet adapter
                          #3)\rdma - ausgehende bytes/s :
                          1464745,8998724

Aswell as in performance Monitor I can use them:
![image](https://user-images.githubusercontent.com/11457386/45039701-6efb9600-b064-11e8-8d18-1dd9508a60a7.png)

I'm using following sample config:
`<perfcounters>
	<perfcounter>
		<category>RDMA-Aktivität</category>
		<name>RDMA - ausgehende Bytes/s</name>
		<instance>hp infiniband fdr-ethernet 10gb-40gb 2-port 544+qsfp ethernet adapter</instance>
		<friendlyname>RDMAOutboundBytes</friendlyname>
		<units>B</units>
		<warning>85%</warning>
		<critical>95%</critical>
		<min>0</min>
		<max>auto</max>
	</perfcounter>
	<perfcounter>
		<category>RDMA-Aktivität</category>
		<name>RDMA - eingehende Bytes/s</name>
		<instance>hp infiniband fdr-ethernet 10gb-40gb 2-port 544+qsfp ethernet adapter</instance>
		<friendlyname>RDMAInboundBytes</friendlyname>
		<units>B</units>
		<warning>85%</warning>
		<critical>95%</critical>
		<min>0</min>
		<max>auto</max>
	</perfcounter>
	<perfcounter>
		<category>RDMA-Aktivität</category>
		<name>RDMA - aktive Verbindungen</name>
		<instance>hp infiniband fdr-ethernet 10gb-40gb 2-port 544+qsfp ethernet adapter</instance>
		<friendlyname>RDMACountConnections</friendlyname>
		<units></units>
		<warning></warning>
		<critical></critical>
		<min>0</min>
		<max>auto</max>
	</perfcounter>
	<perfcounter>
		<category>RDMA-Aktivität</category>
		<name>RDMA - Verbindungsfehler</name>
		<instance>hp infiniband fdr-ethernet 10gb-40gb 2-port 544+qsfp ethernet adapter</instance>
		<friendlyname>RDMAConnectionErrors</friendlyname>
		<units></units>
		<warning></warning>
		<critical></critical>
		<min>0</min>
		<max>auto</max>
	</perfcounter>
</perfcounters> `

Have you any ideas what I'm doing wrong?  I think it hase something to do with the german translation (German Windows Server 2016). What do you guess?

Thanks in advance,
Constantin

**Comment by juangranados** [comment]
Hi @Constey!

I do not have any server RDMA compatible, but I think you should use english counter names:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<perfcounters>
   <perfcounter>
      <category>RDMA Activity</category>
      <name>RDMA Inbound Bytes/sec</name>
      <instance>hp infiniband fdr-ethernet 10gb-40gb 2-port 544+qsfp ethernet adapter</instance>
      <friendlyname>RDMAInboundBytes</friendlyname>
      <units>B</units>
      <warning>85%</warning>
      <critical>95%</critical>
      <min>0</min>
      <max>100</max>
   </perfcounter>
</perfcounters>
```
```powershell 
PS > Get-Counter -ListSet "RDMA*" | Select-Object -ExpandProperty Counter
\RDMA Activity(*)\RDMA Outbound Frames/sec
\RDMA Activity(*)\RDMA Inbound Frames/sec
\RDMA Activity(*)\RDMA Outbound Bytes/sec
\RDMA Activity(*)\RDMA Inbound Bytes/sec
\RDMA Activity(*)\RDMA Completion Queue Errors
\RDMA Activity(*)\RDMA Active Connections
\RDMA Activity(*)\RDMA Connection Errors
\RDMA Activity(*)\RDMA Failed Connection Attempts
\RDMA Activity(*)\RDMA Accepted Connections
\RDMA Activity(*)\RDMA Initiated Connections
```
Let me know if it works this way.

Regards!

**Comment by Constey** [comment]
You got it. Using the english translation it works well... Should be noticed somewhere. Thanks for your help :-)

**Comment by juangranados** [comment]
Great! I updated the doc to reflect this requirement.

Thanks for your response.
